### ISSUE TITLE
Crash During Startup

### ISSUE THREAD

**Issue by Darkmega18** [RiskyKen/Armourers-Workshop#29]
Hey risky hopefully you get this nutted out soon. But I get this crash upon starting my game, I'm using the second latest minecraft forge there is. Version 1395. something about no class definitions and stuff. :< I'd use paste bin, but it's just one report, so shouldn't be too bad... right?

edit: also, confirmed to work with previous version of 1.7.10-0.29.2.76 but then the latest that you have on curse-forge at the time of this post don't want to work due to this crash.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/05/15 3:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: riskyken/armourersWorkshop/api/common/equipment/EnumEquipmentType
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:536)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:253)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: riskyken/armourersWorkshop/api/common/equipment/EnumEquipmentType
	at net.mcft.copy.betterstorage.addon.armourersworkshop.AWAddon.setupConfig(AWAddon.java:32)
	at net.mcft.copy.betterstorage.addon.Addon.setupConfigsAll(Addon.java:26)
	at net.mcft.copy.betterstorage.BetterStorage.preInit(BetterStorage.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
	... 10 more
Caused by: java.lang.ClassNotFoundException: riskyken.armourersWorkshop.api.common.equipment.EnumEquipmentType
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 723349688 bytes (689 MB) / 1389363200 bytes (1325 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 153 mods loaded, 152 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.130.1395} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1395} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized
	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-beta-28} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.6.39} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	MobiusCore{1.2.4} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized
	Botania{r1.6-185} [Botania] (Botania r1.6-185.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized
	technom{0.9.0} [Technomancy] (1.7.10 Technomancy 0.9.0.jar) Unloaded->Constructed->Pre-initialized
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized
	zeldaswordskills{1.7.10-2.2.5.c} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.2.5.c.jar) Unloaded->Constructed->Pre-initialized
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized
	securitycraft{v1.7.3} [SecurityCraft] ([1.7.10] SecurityCraft 1.7.3.jar) Unloaded->Constructed->Pre-initialized
	IC2{2.2.714-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.714-experimental.jar) Unloaded->Constructed->Pre-initialized
	advancedgenetics{1.5.7} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) Unloaded->Constructed->Pre-initialized
	AetherCraft{1.5.0.82} [AetherCraft] (AetherCraft-1.7.10-1.5.0.82.jar) Unloaded->Constructed->Pre-initialized
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-beta-28} [Applied Energistics 2] (appliedenergistics2-rv2-beta-28.jar) Unloaded->Constructed->Pre-initialized
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
	armourersWorkshop{1.7.10-0.31.2.82} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.31.2.82.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-395.jar) Unloaded->Constructed->Pre-initialized
	asielib{0.3.6} [asielib] (AsieLib-1.7.10-0.3.6.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.1.3} [iChunUtil] (iChunUtil-4.1.3.jar) Unloaded->Constructed->Pre-initialized
	Grinder{4.0.0} [Grinder] (AttachableGrinder-4.0.0.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Automagy{0.23} [Automagy] (Automagy-1.7.10-0.23.jar) Unloaded->Constructed->Pre-initialized
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
	tennox_bacteria{2.3.2} [Bacteria Mod] (BacteriaMod-1.7.2-2.3.2.jar) Unloaded->Constructed->Pre-initialized
	betterstorage{0.12.0.124} [BetterStorage] (BetterStorage-1.7.10-0.12.0.124.jar) Unloaded->Constructed->Errored
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	cannibalism{1.0.2} [Cannibalism] (Cannibalism-1.0.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ChestTransporter{2.0.1} [Chest Transporter] (ChestTransporter-2.0.1-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.3.9.36} [Chisel 2] (Chisel2-2.3.9.36.jar) Unloaded->Constructed->Pre-initialized
	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) Unloaded->Constructed->Pre-initialized
	clockworkphase{1.7.10_1.0c} [Clockwork Phase] (clockworkphase-1.7.10_1.0c.jar) Unloaded->Constructed->Pre-initialized
	customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) Unloaded->Constructed->Pre-initialized
	lootablebodies{1.3.2} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.2-backport.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.5.12} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.12-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.16.77} [ProjectRed] (ProjectRed-1.7.10-4.5.16.77-Base.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.8.2a.jar) Unloaded->Constructed->Pre-initialized
	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V6f.jar) Unloaded->Constructed->Pre-initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized
	Mekanism{8.1.2} [Mekanism] (Mekanism-1.7.10-8.1.2.229.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.8.351} [Ender IO] (EnderIO-1.7.10-2.2.8.351.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized
	EnderZoo{1.7.10-1.0.9.18} [Ender Zoo] (EnderZoo-1.7.10-1.0.9.18.jar) Unloaded->Constructed->Pre-initialized
	enhancedportals{3.0.10} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed->Pre-initialized
	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed->Pre-initialized
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
	ForbiddenMagic{1.7.10-0.561} [Forbidden Magic] (Forbidden Magic-1.7.10-0.561.jar) Unloaded->Constructed->Pre-initialized
	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	gunreeds{V0.1 - 1.7.10} [Gunpowder Reeds] (Gunpowder Reeds-V0.1 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	healthpack{V0.1 - 1.7.10} [Health Pack] (Health Pack-V0.1 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	HardcoreQuesting{The Journey (4.2.2)} [Hardcore Questing Mode] (HQM-The Journey (4.2.2).jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	lootplusplus{0.13_beta3} [Loot++] (Loot++-0.13_beta3.jar) Unloaded->Constructed->Pre-initialized
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized
	mcheli{0.10.5} [MC Helicopter] (mcheli) Unloaded->Constructed->Pre-initialized
	MekanismGenerators{8.1.2} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.2.229.jar) Unloaded->Constructed->Pre-initialized
	MekanismTools{8.1.2} [MekanismTools] (MekanismTools-1.7.10-8.1.2.229.jar) Unloaded->Constructed->Pre-initialized
	meteors{2.14.2} [Falling Meteors] (meteors-1.7.10-2.14.2.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.5.16.77} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.16.77-World.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized
	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized
	MobProperties{0.3.5} [Mob Properties] (MobProperties-1.7.10-0.3.5.jar) Unloaded->Constructed->Pre-initialized
	musicchoices{1.0_beta5} [Music Choices] (MusicChoices-1.0_beta5-client.jar) Unloaded->Constructed->Pre-initialized
	mwaw{1.7.10-0.0.5} [Elemental Witch Mod] (mwaw-1.7.10-0.0.5.jar) Unloaded->Constructed->Pre-initialized
	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized
	New Biospheres Mod{0.8} [New Biospheres Mod] (NewBiospheresMod-1.7.x-0.8.jar) Unloaded->Constructed->Pre-initialized
	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29-client.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized
	openmodularturrets{1.3.4} [Open Modular Turrets] (OpenModularTurrets-1.7.10-1.3.4-27.jar) Unloaded->Constructed->Pre-initialized
	MapWriter{2.1.2} [MapWriter] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Opis{1.2.4} [Opis] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.5.16.77} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.5.16.77} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.5.16.77} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.16.77-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.5.16.77} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.16.77-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.5.16.77} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.16.77-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.5.16.77} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.16.77-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized
	rivalrebels{1.7.10G} [Rival Rebels] (rivalrebels-1.7.10G.jar) Unloaded->Constructed->Pre-initialized
	Schematica{1.7.5.117} [Schematica] (Schematica-1.7.10-1.7.5.117-universal-client.jar) Unloaded->Constructed->Pre-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed->Pre-initialized
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded->Constructed->Pre-initialized
	SSR{rc3} [Soul Shards Reborn] (SSR-rc3.jar) Unloaded->Constructed->Pre-initialized
	statues{2.1.4} [Statues] (statues-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7-client.jar) Unloaded->Constructed->Pre-initialized
	thaumicinfusion{3.966} [Thaumic Infusion] (ThaumicInfusion-3.966.jar) Unloaded->Constructed->Pre-initialized
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized
	Torched{4.0.0} [Torched] (Torched-4.0.0.jar) Unloaded->Constructed->Pre-initialized
	Torcherino{2.1s} [Torcherino] (Torcherino-1.7.10-2.1s.jar) Unloaded->Constructed->Pre-initialized
	THKaguyaMod{2.90-1.7.10} [Itutu no Nandai MOD+ (Touhou Items Mod)] (Touhou MOD+ ver2.90-1.7.10.zip) Unloaded->Constructed->Pre-initialized
	TrailMix{4.0.0} [TrailMix] (TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized
	UsefulTNT{beta} [Useful TNT] (UsefulTNT 1.7.10 V6a.jar) Unloaded->Constructed->Pre-initialized
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized
	reaper_waterpipe{1.11} [Water Pipe mod] (Waterpipe1.11[1.7.10].jar) Unloaded->Constructed->Pre-initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized
	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized
	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized
	asielibcore{} [AsieLib CoreMod] (minecraft.jar) Unloaded->Disabled
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.09' Renderer: 'GeForce GTX 560 Ti/PCIe/SSE2'
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	AE2 Version: beta rv2-beta-28 for Forge 10.13.2.1291
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8

**Comment by RiskyKen** [comment]
BetterStorage is using an old API, it has been fixed in BetterStorage but a new build is not out yet. :(

You can wait for BetterStorage to update or back-date Armourer's Workshop to 29.2.76.

Pokes @copygirl

**Comment by copygirl** [comment]
Fiiiine...

**Comment by RiskyKen** [comment]
Fixed with build 126 of BetterStorage https://github.com/copygirl/BetterStorage/releases/tag/v0.13.1.126

**Comment by Darkmega18** [comment]
yay! :D

**Comment by copygirl** [comment]
@RiskyKen did all the work, I just took my sweet time releasing a new version.
